image:
#  repository: registry.hub.docker.com/r/fyb3roptik/threadfin
  repository: fyb3roptik/threadfin
  tag: 1.0.18@sha256:462a4ba7bab1501c4f3e40a03835ac6de5f8d75b2b51edcff555f414fe8bee00
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 34400
        targetPort: 34400
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
