image:
#  repository: registry.hub.docker.com/r/fyb3roptik/threadfin
  repository: fyb3roptik/threadfin
  tag: 1.0.26@sha256:73becf8f4e4d511810b8481883edb7b35a1fb1cc7e47cfe028a1bc504001511b
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 34400
        targetPort: 34400

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THREADFIN_HOME: "/home/threadfin"
            THREADFIN_BIN:  "/home/threadfin/bin"
            THREADFIN_CONF: "/home/threadfin/conf"
#            THREADFIN_BRANCH: "main"
#            THREADFIN_DEBUG: "0"
#            THREADFIN_PORT: "34400"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  open:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
